[CMake] Add Qt5::Gui private include dirs to CMakeLists.txt
I added ${Qt5Gui_PRIVATE_INCLUDE_DIRS} to CMakeLists.txt because GCC on
MSYS2 (MinGW-w64) can't find "qpa/qplatformnativeinterface.h" showing
this error:

fatal error: qpa/qplatformnativeinterface.h: No such file or directory